# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Random Sequence Of Letters
#tagline:             'Musings on topics of personal interest'
description:         'Varied musings on topics of personal interest.'
url:                 http://blog.rsol.ca
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Elliott Noel
  url:               https://twitter.com/SkipperEl
  email:             blog@rsol.ca

# Custom vars
version:             1.0.0
